export enum ErrorMessage {
  MEETINGS_IS_NOT_FOUND = 'MEETING IS NOT FOUND',
  CREDENTIALS_ERROR = 'INVALID CREDENTIALS',
  MEETING_MEMBER_NOT_FOUND = 'MEETING MEMBER IS NOT FOUND OR IS NOT ACTIVE',
  USER_CONNECTED = 'THE USER IS ALREADY CONNECTED ON THE MEETING',
}
